title: Selegi — Currency of the Islands
<link rel="stylesheet" href="/assets/css/custom.css">
description: Selegi is a community-first digital currency for the Samoan archipelago, built on Stellar for fast, low-fee payments.
